### PR TITLE
Override subkeys

### PR DESCRIPTION
**Pull request by LeReverandNox**
Hey guys,

I needed a feature so I can override an already existing key prefix, without having to delete it manually.

I didn't find a clean way to write unit test for this feature with out-of-tree data, please let me know if there's a good approach.

Thanks :)

### CODE REVIEW

**Comment by LeReverandNox** [comment]
Hi @radeksimko ,
We really need this feature in our workflow soon.
Do you want me to improve this PR ? :)

Thanks !

**Comment by apparentlymart** [comment]
Hi @LeReverandNox! Sorry for the long silence here... our attention was diverted elsewhere during the 0.11 development cycle, so we didn't notice this PR until now. :confounded:

We generally prefer to model this sort of thing via the import feature rather than via an "override" flag. In this case that might look like this:

```
$ terraform import consul_key_prefix.example myapp/config/
```

Having an explicit import step is preferred because it makes it very clear that an existing resource is being transferred into management by Terraform, as opposed to a new resource being created.

Would that work for what you want to achieve here? You mentioned that you need this for something in your workflow, so if you're able to share more details on what you're trying to do here that would be useful context for reviewing this change.

Thanks for working on this, and sorry it went unnoticed for so long.

**Comment by pearkes** [comment]
@LeReverandNox do you have any thoughts on the above comment?

**Comment by pearkes** [comment]
@LeReverandNox given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.

**Pull request closed without merging**
