### PR TITLE
Add consul_acl_token and consul_acl_token_secret_id data sources

### PR DESCRIPTION
**Pull request by marimp**
Hi there.
The feature will address the original issue terraform-providers#126 of accessing the secret_id of the consul acl token.
For this purpose a new data source was implemented dataSourceConsulACLToken() .

These are files that implement the data source

    consul/data_source_consul_acl_token.go
    consul/data_source_consul_acl_token_test.go

the required filter parameters and the related outputs

// Datasource predicates
aclTokenAccessorID = "accessor_id"

// Output
aclTokenSecretID    = "secret_id"
aclTokenDescription = "description"
aclTokenPolicies    = "policies"
aclTokenLocal       = "local"

The related documentation file:

    website/docs/assets/d/acl_token.html.markdown

The test related to the new feature was correctly performed:

make testacc
=== RUN   TestAccDataACLToken_basic
--- PASS: TestAccDataACLToken_basic (0.07s)
...

Thanks
Regards

### CODE REVIEW

**Comment by marimp** [comment]
Hi all,
have you got updates regarding this pull request?

Great Thanks
Regards

**Comment by remilapeyre** [comment]
Hi @marimp, thanks for opening this PR. In order to avoid writing the secret ID to the Terraform state, I split your PR in two data source, one that fetch the information of a given token, that can always be used with no security risk, and another that fetch only the secret ID and support being encrypted. This will cover the use case of #126 without writing the secret ID to the state for all users that don't need it.

**Comment by marimp** [comment]
Hi @remilapeyre ,
thanks for your improvement.
I see that the build is not working on master branch (due to an ambiguous import: of github.com/hashicorp/consul/api). Could you fix before integrate the code?

Great Thanks
Tregards

**Comment by remilapeyre** [comment]
Hi @marimp, I just tried a1b17bcf4dbe1e5911faa59aba1150001310a12b and fb70af9b16eb277c9a4b167bf95ff750458f4d45 and they both seem to build without issue and pass the tests (`make && make test && make testacc`).

Am I missing something?

**Comment by marimp** [comment]
Hi @remilapeyre, 
I wrongly removed my forked branch and so this pull request was lost.
Have you got the possibility to recover?
Probably you have all code (my and yours).

Great Thanks
Regards

**Comment by remilapeyre** [comment]
Hi @marimp, I opened a new PR at https://github.com/terraform-providers/terraform-provider-consul/pull/137

> I wrongly removed my forked branch and so this pull request was lost.

LPT: It's actually pretty rare to delete something in Git, your work probably was in a dangling commit and would only have been definitely deleted when it would have been older then 30 days or so. You should be able to run `git reflog` and to see the `a4207b6` commit. You can then create a new branch from it by running `git checkout -b my-new-branch a4207b6`.

**Pull request closed without merging**
