### PR TITLE
Add roles argument to consul_acl_token

### PR DESCRIPTION
**Pull request by remilapeyre**
Closes https://github.com/terraform-providers/terraform-provider-consul/issues/178

### CODE REVIEW

**Comment by ltagliamonte-dd** [comment]
@remilapeyre there are failing tests in this PR

**Comment by remilapeyre** [comment]
Yes, it's because of a few changes with Consul 1.7, I fixed that in #181

**Comment by ltagliamonte-dd** [comment]
cool @remilapeyre , any ETA on merging this?

**Comment by remilapeyre** [comment]
Hi @ltagliamonte-dd, I plan to make a new release in the next few days with the new features for Consul 1.7.

**Pull request merged**
